/* deep.js — the Deep Atlas loader.
   The curated core lives in js/items/*.js and is always loaded.
   The deep tail (hundreds of thousands of works generated by
   tools/build_deep_atlas.py) lives in data/deep/ as shard files,
   injected on demand as plain <script> tags — which works from file://. */

"use strict";

/* Shards call DEEPDATA.push({l:leafId, r:[[title,year,creator,pop,imp,fld,"tag|tag"],...]}) */
window.DEEPDATA = {
  push: function (pack) {
    if (window.ATLAS && ATLAS.addDeepRows) ATLAS.addDeepRows(pack.l, pack.r);
  }
};

window.DEEP = (function () {
  var loadedShards = {};   // leafId -> number of shards absorbed
  var inFlight = {};

  function manifest() { return window.DEEPINDEX || {}; }
  function info(leaf) { return manifest()[leaf] || null; }
  function isLoaded(leaf) {
    var i = info(leaf);
    return !i || (loadedShards[leaf] || 0) >= i.s;
  }
  function remaining(leaf) {
    var i = info(leaf);
    if (!i) return 0;
    var done = loadedShards[leaf] || 0;
    return done >= i.s ? 0 : i.n - done * 2500 > 0 ? i.n - Math.min(i.n, done * 2500) : 0;
  }
  function grandTotal() {
    var m = manifest(), t = 0;
    Object.keys(m).forEach(function (k) { t += m[k].n; });
    return t;
  }
  function countForLeaves(leafIds) {
    var m = manifest(), t = 0;
    leafIds.forEach(function (k) { if (m[k]) t += m[k].n; });
    return t;
  }
  function remainingForLeaves(leafIds) {
    var t = 0;
    leafIds.forEach(function (k) { t += remaining(k); });
    return t;
  }

  function inject(src, cb) {
    var s = document.createElement("script");
    s.src = src;
    s.onload = function () { s.remove(); cb(null); };
    s.onerror = function () { s.remove(); console.warn("[deep] failed shard " + src); cb(new Error(src)); };
    document.head.appendChild(s);
  }

  function loadLeaf(leaf, cb) {
    var i = info(leaf);
    if (!i || isLoaded(leaf)) { cb && cb(); return; }
    if (inFlight[leaf]) { inFlight[leaf].push(cb); return; }
    inFlight[leaf] = cb ? [cb] : [];
    var next = loadedShards[leaf] || 0;
    (function step() {
      if (next >= i.s) {
        var cbs = inFlight[leaf]; delete inFlight[leaf];
        cbs.forEach(function (f) { f && f(); });
        return;
      }
      inject("data/deep/" + leaf + "-" + next + ".js" + (window.DEEPV ? "?v=" + window.DEEPV : ""), function () {
        next++;
        loadedShards[leaf] = next;
        // yield to the event loop between shards (rAF stalls in hidden tabs)
        setTimeout(step, 0);
      });
    })();
  }

  function loadLeaves(leafIds, onProgress, onDone) {
    var todo = leafIds.filter(function (l) { return !isLoaded(l); });
    var total = todo.length, done = 0;
    if (!total) { onDone && onDone(); return; }
    (function step() {
      if (!todo.length) { onDone && onDone(); return; }
      var leaf = todo.shift();
      loadLeaf(leaf, function () {
        done++;
        onProgress && onProgress(done, total, leaf);
        step();
      });
    })();
  }

  function loadAll(onProgress, onDone) {
    loadLeaves(Object.keys(manifest()), onProgress, onDone);
  }

  return {
    info: info, isLoaded: isLoaded, remaining: remaining,
    grandTotal: grandTotal, countForLeaves: countForLeaves,
    remainingForLeaves: remainingForLeaves,
    loadLeaf: loadLeaf, loadLeaves: loadLeaves, loadAll: loadAll
  };
})();
