/* The Moving Image */
"use strict";

/* ---- Film — The Golden Ages (to 1975) ---- */
I("film-golden","A Trip to the Moon",1902,"Georges Méliès",48,90,94,["silent","first"],["film-buff","criterion-core"]);
I("film-golden","Metropolis",1927,"Fritz Lang",44,90,94,["silent","dystopia","city"],["film-buff","criterion-core","dystopia-canon"]);
I("film-golden","City Lights",1931,"Charlie Chaplin",50,88,92,["silent","comedy"],["film-buff","criterion-core"]);
I("film-golden","Modern Times",1936,"Charlie Chaplin",52,88,92,["silent","machine"],["film-buff","criterion-core"]);
I("film-golden","King Kong",1933,"Merian C. Cooper",62,84,86,["monster","spectacle"],["film-buff","blockbuster-core"]);
I("film-golden","Gone with the Wind",1939,"Victor Fleming",68,88,90,["epic","civil-war"],["film-buff"]);
I("film-golden","The Wizard of Oz",1939,"Victor Fleming",86,92,94,["fantasy","technicolor"],["blockbuster-core","kids-canon"]);
I("film-golden","Citizen Kane",1941,"Orson Welles",62,97,100,["newspaper","rosebud"],["film-buff","criterion-core"]);
I("film-golden","Casablanca",1942,"Michael Curtiz",70,94,97,["romance","war"],["film-buff"]);
I("film-golden","It's a Wonderful Life",1946,"Frank Capra",68,88,90,["christmas","angel"],["film-buff"]);
I("film-golden","Bicycle Thieves",1948,"Vittorio De Sica",36,90,94,["neorealism","rome"],["criterion-core","world-cinema"]);
I("film-golden","Sunset Boulevard",1950,"Billy Wilder",42,90,93,["hollywood","noir"],["film-buff","criterion-core","crime-noir"]);
I("film-golden","Singin' in the Rain",1952,"Kelly & Donen",64,92,94,["musical","hollywood"],["film-buff","musical-theatre"]);
I("film-golden","Tokyo Story",1953,"Yasujirō Ozu",28,92,96,["family","stillness"],["criterion-core","world-cinema"]);
I("film-golden","Seven Samurai",1954,"Akira Kurosawa",52,95,98,["samurai","village"],["criterion-core","world-cinema","film-buff"]);
I("film-golden","Rashomon",1950,"Akira Kurosawa",42,92,95,["perspective","truth"],["criterion-core","world-cinema"]);
I("film-golden","Rear Window",1954,"Alfred Hitchcock",56,90,93,["voyeurism","suspense"],["film-buff"]);
I("film-golden","Vertigo",1958,"Alfred Hitchcock",50,94,97,["obsession","spiral"],["film-buff","criterion-core"]);
I("film-golden","North by Northwest",1959,"Alfred Hitchcock",52,88,91,["chase","cropduster"],["film-buff"]);
I("film-golden","Psycho",1960,"Alfred Hitchcock",74,94,96,["shower","twist"],["film-buff","horror-canon"]);
I("film-golden","Some Like It Hot",1959,"Billy Wilder",54,88,91,["comedy","disguise"],["film-buff"]);
I("film-golden","12 Angry Men",1957,"Sidney Lumet",62,90,93,["jury","room"],["film-buff"]);
I("film-golden","The Seventh Seal",1957,"Ingmar Bergman",38,90,94,["death","chess"],["criterion-core","arthouse"]);
I("film-golden","Persona",1966,"Ingmar Bergman",30,88,93,["identity","faces"],["criterion-core","arthouse"]);
I("film-golden","Breathless",1960,"Jean-Luc Godard",34,88,92,["new-wave","jump-cut"],["criterion-core","world-cinema"]);
I("film-golden","The 400 Blows",1959,"François Truffaut",32,88,92,["new-wave","childhood"],["criterion-core","world-cinema"]);
I("film-golden","8½",1963,"Federico Fellini",32,90,94,["meta","director"],["criterion-core","arthouse"]);
I("film-golden","La Dolce Vita",1960,"Federico Fellini",36,88,92,["rome","decadence"],["criterion-core","arthouse"]);
I("film-golden","Lawrence of Arabia",1962,"David Lean",50,92,95,["epic","desert"],["film-buff","visual-maximalism"]);
I("film-golden","Dr. Strangelove",1964,"Stanley Kubrick",56,92,95,["satire","bomb"],["film-buff","cold-war"]);
I("film-golden","2001: A Space Odyssey",1968,"Stanley Kubrick",70,97,99,["space","monolith"],["film-buff","space-scifi","visual-maximalism","criterion-core"]);
I("film-golden","The Good, the Bad and the Ugly",1966,"Sergio Leone",64,90,93,["western","standoff"],["film-buff"],["the-good-the-bad-and-the-ugly-score-1966"]);
I("film-golden","Once Upon a Time in the West",1968,"Sergio Leone",42,86,90,["western","harmonica"],["film-buff"]);
I("film-golden","Andrei Rublev",1966,"Andrei Tarkovsky",22,88,94,["icon-painter","faith"],["criterion-core","arthouse","russian-lit"]);
I("film-golden","Solaris",1972,"Andrei Tarkovsky",28,86,92,["space","memory"],["criterion-core","arthouse","space-scifi"]);
I("film-golden","The Godfather",1972,"Francis Ford Coppola",84,98,100,["mafia","family"],["film-buff","blockbuster-core","crime-noir"]);
I("film-golden","The Godfather Part II",1974,"Francis Ford Coppola",72,96,98,["mafia","parallel"],["film-buff","crime-noir"]);
I("film-golden","Chinatown",1974,"Roman Polanski",44,90,93,["noir","water"],["film-buff","crime-noir"]);
I("film-golden","One Flew Over the Cuckoo's Nest",1975,"Miloš Forman",64,92,94,["institution","rebellion"],["film-buff"]);
I("film-golden","Jaws",1975,"Steven Spielberg",82,92,94,["shark","summer"],["blockbuster-core"]);
I("film-golden","A Clockwork Orange",1971,"Stanley Kubrick",58,88,91,["dystopia","ultraviolence"],["film-buff","cult-canon","dorm-canon"]);
I("film-golden","The Holy Mountain",1973,"Alejandro Jodorowsky",22,72,82,["surreal","alchemy"],["cult-canon","visual-maximalism","arthouse"]);

/* ---- Film — Modern Canon ---- */
I("film-modern","Taxi Driver",1976,"Martin Scorsese",58,92,95,["alienation","new-york"],["film-buff","dorm-canon"]);
I("film-modern","Apocalypse Now",1979,"Francis Ford Coppola",58,93,96,["vietnam","river"],["film-buff","wwii-memory"]);
I("film-modern","Raging Bull",1980,"Martin Scorsese",44,90,93,["boxing","self-destruction"],["film-buff","fight-fans"]);
I("film-modern","Goodfellas",1990,"Martin Scorsese",70,94,96,["mafia","rise-fall"],["film-buff","dorm-canon","crime-noir"]);
I("film-modern","Blade Runner",1982,"Ridley Scott",60,92,96,["cyberpunk","replicants"],["cyberpunk","film-buff","cult-canon"],["blade-runner-score-1982"]);
I("film-modern","The Shining",1980,"Stanley Kubrick",74,92,95,["hotel","madness"],["film-buff","horror-canon"]);
I("film-modern","Full Metal Jacket",1987,"Stanley Kubrick",56,84,87,["vietnam","drill"],["film-buff"]);
I("film-modern","Schindler's List",1993,"Steven Spielberg",74,96,97,["holocaust","list"],["film-buff","wwii-memory"]);
I("film-modern","The Shawshank Redemption",1994,"Frank Darabont",88,92,95,["prison","hope"],["blockbuster-core","dorm-canon"]);
I("film-modern","The Green Mile",1999,"Frank Darabont",72,80,84,["prison","miracle"],["blockbuster-core"],[],"Darabont's other prison film — the gentler, stranger one.");
I("film-modern","Pulp Fiction",1994,"Quentin Tarantino",84,95,97,["nonlinear","crime"],["film-buff","dorm-canon","cult-canon"]);
I("film-modern","Reservoir Dogs",1992,"Quentin Tarantino",58,84,87,["heist","standoff"],["dorm-canon","cult-canon"]);
I("film-modern","Kill Bill: Vol. 1",2003,"Quentin Tarantino",64,80,83,["revenge","katana"],["dorm-canon"]);
I("film-modern","Inglourious Basterds",2009,"Quentin Tarantino",68,82,85,["ww2","revision"],["film-buff","wwii-memory"]);
I("film-modern","Fight Club",1999,"David Fincher",80,88,91,["masculinity","twist"],["dorm-canon","cult-canon"],["fight-club-1996"]);
I("film-modern","Se7en",1995,"David Fincher",70,86,89,["serial-killer","box"],["crime-noir","dorm-canon"]);
I("film-modern","The Social Network",2010,"David Fincher",64,84,88,["facebook","betrayal"],["film-buff"],["the-social-network-score-2010","facebook-opens-to-everyone-2006"]);
I("film-modern","Zodiac",2007,"David Fincher",46,80,86,["obsession","cipher"],["crime-noir","true-crime"]);
I("film-modern","The Silence of the Lambs",1991,"Jonathan Demme",70,90,92,["profiler","lecter"],["crime-noir","horror-canon"]);
I("film-modern","Forrest Gump",1994,"Robert Zemeckis",86,86,88,["history","innocence"],["blockbuster-core"]);
I("film-modern","Titanic",1997,"James Cameron",94,90,92,["romance","disaster"],["blockbuster-core"],["the-sinking-of-the-titanic-1912","my-heart-will-go-on-1997"]);
I("film-modern","The Truman Show",1998,"Peter Weir",70,86,90,["simulation","dome"],["dorm-canon"],[],"Life is just media simulator.");
I("film-modern","American Beauty",1999,"Sam Mendes",58,78,80,["suburbia","plastic-bag"],["film-buff"]);
I("film-modern","Gladiator",2000,"Ridley Scott",78,84,86,["rome","arena"],["blockbuster-core"]);
I("film-modern","Memento",2000,"Christopher Nolan",58,84,88,["memory","reverse"],["dorm-canon","film-buff"]);
I("film-modern","The Prestige",2006,"Christopher Nolan",62,82,86,["magicians","obsession"],["dorm-canon"]);
I("film-modern","Inception",2010,"Christopher Nolan",84,88,91,["dreams","heist"],["blockbuster-core","dorm-canon"]);
I("film-modern","Interstellar",2014,"Christopher Nolan",82,86,89,["space","time","love"],["blockbuster-core","space-scifi"],["interstellar-score-2014"]);
I("film-modern","Oppenheimer",2023,"Christopher Nolan",76,84,87,["bomb","biography"],["blockbuster-core","film-buff"],["the-trinity-test-1945"]);
I("film-modern","Eternal Sunshine of the Spotless Mind",2004,"Michel Gondry",58,86,90,["memory","erasure"],["arthouse","dorm-canon"]);
I("film-modern","No Country for Old Men",2007,"Coen Brothers",60,88,91,["fate","coin-toss"],["film-buff","crime-noir"],["no-country-for-old-men-2005"]);
I("film-modern","Fargo",1996,"Coen Brothers",54,86,90,["snow","crime"],["film-buff","crime-noir"],["fargo-2014"]);
I("film-modern","There Will Be Blood",2007,"Paul Thomas Anderson",50,90,94,["oil","milkshake"],["film-buff"]);
I("film-modern","The Departed",2006,"Martin Scorsese",66,82,85,["moles","boston"],["film-buff","crime-noir"]);
I("film-modern","Whiplash",2014,"Damien Chazelle",62,82,87,["drums","tempo"],["film-buff"]);
I("film-modern","La La Land",2016,"Damien Chazelle",72,78,82,["musical","la"],["blockbuster-core","musical-theatre"]);
I("film-modern","Mad Max: Fury Road",2015,"George Miller",70,88,92,["chase","wasteland"],["blockbuster-core","visual-maximalism"]);
I("film-modern","Parasite",2019,"Bong Joon-ho",74,92,95,["class","house"],["world-cinema","film-buff"]);
I("film-modern","Memories of Murder",2003,"Bong Joon-ho",38,84,90,["procedural","korea"],["world-cinema","crime-noir"]);
I("film-modern","Get Out",2017,"Jordan Peele",70,86,89,["social-horror","sunken-place"],["horror-canon","a24-wave"]);
I("film-modern","Moonlight",2016,"Barry Jenkins",50,84,88,["identity","triptych"],["a24-wave","film-buff"]);
I("film-modern","Everything Everywhere All at Once",2022,"Daniels",68,84,87,["multiverse","family"],["a24-wave","dorm-canon"]);
I("film-modern","The Grand Budapest Hotel",2014,"Wes Anderson",62,82,86,["symmetry","caper"],["arthouse","film-buff"]);
I("film-modern","Lost in Translation",2003,"Sofia Coppola",54,80,84,["tokyo","whisper"],["arthouse"]);
I("film-modern","Her",2013,"Spike Jonze",56,82,86,["ai","loneliness"],["arthouse","dorm-canon"]);
I("film-modern","Big Fish",2003,"Tim Burton",52,74,78,["tall-tales","father"],["visual-maximalism"],[],"A life retold as myth until the myth is the truer record.");
I("film-modern","The Fountain",2006,"Darren Aronofsky",34,68,76,["death","tree"],["visual-maximalism","arthouse","cult-canon"]);
I("film-modern","Requiem for a Dream",2000,"Darren Aronofsky",56,78,82,["addiction","montage"],["dorm-canon","arthouse"]);
I("film-modern","Black Swan",2010,"Darren Aronofsky",62,80,84,["ballet","double"],["film-buff"],["swan-lake-1877"]);
I("film-modern","The Fall",2006,"Tarsem Singh",28,52,70,["frame-story","stuntman","painterly"],["visual-maximalism","cult-canon","arthouse"],["the-cell-2000","pans-labyrinth-2006","baraka-1992","the-princess-bride-1987","big-fish-2003","the-holy-mountain-1973"],"Shot in 20-odd countries; a bedtime story told to a child with the teller bleeding through. The test case for this whole atlas.");
I("film-modern","The Cell",2000,"Tarsem Singh",34,58,68,["mindscape","serial-killer"],["visual-maximalism","cult-canon"]);
I("film-modern","American Psycho",2000,"Mary Harron",64,76,80,["satire","business-card"],["cult-canon","dorm-canon"],["american-psycho-1991"]);
I("film-modern","Trainspotting",1996,"Danny Boyle",60,82,86,["addiction","choose-life"],["cult-canon","dorm-canon"],["trainspotting-1993"]);
I("film-modern","Slumdog Millionaire",2008,"Danny Boyle",66,76,78,["mumbai","quiz"],["blockbuster-core"]);
I("film-modern","The Sixth Sense",1999,"M. Night Shyamalan",76,82,84,["twist","ghosts"],["blockbuster-core","horror-canon"]);
I("film-modern","Good Will Hunting",1997,"Gus Van Sant",70,80,82,["genius","boston"],["blockbuster-core","dorm-canon"]);
I("film-modern","Dead Poets Society",1989,"Peter Weir",68,80,82,["carpe-diem","school"],["blockbuster-core","dorm-canon"]);
I("film-modern","The Big Lebowski",1998,"Coen Brothers",60,80,84,["dude","bowling"],["cult-canon","dorm-canon"]);
I("film-modern","Donnie Darko",2001,"Richard Kelly",52,72,78,["time-loop","rabbit"],["cult-canon","dorm-canon"]);
I("film-modern","Primer",2004,"Shane Carruth",22,60,72,["time-travel","garage"],["cult-canon"]);
I("film-modern","Drive",2011,"Nicolas Winding Refn",54,74,78,["neon","scorpion"],["cult-canon","arthouse"]);
I("film-modern","Blade Runner 2049",2017,"Denis Villeneuve",56,82,86,["cyberpunk","memory"],["cyberpunk","film-buff","visual-maximalism"]);
I("film-modern","Arrival",2016,"Denis Villeneuve",62,84,88,["language","time"],["space-scifi","film-buff"]);

/* ---- Film — Spectacle & Franchise ---- */
I("film-blockbuster","Star Wars: A New Hope",1977,"George Lucas",95,96,98,["space-opera","force"],["blockbuster-core","sff-canon"],["star-wars-suite-1977"]);
I("film-blockbuster","The Empire Strikes Back",1980,"Irvin Kershner",88,92,95,["space-opera","father"],["blockbuster-core","sff-canon"]);
I("film-blockbuster","Return of the Jedi",1983,"Richard Marquand",82,84,86,["space-opera","ewoks"],["blockbuster-core"]);
I("film-blockbuster","The Phantom Menace",1999,"George Lucas",78,64,66,["prequel","podrace"],["blockbuster-core","meme-canon"]);
I("film-blockbuster","The Force Awakens",2015,"J.J. Abrams",80,68,70,["sequel","legacy"],["blockbuster-core"]);
I("film-blockbuster","Raiders of the Lost Ark",1981,"Steven Spielberg",80,90,92,["adventure","ark"],["blockbuster-core"]);
I("film-blockbuster","E.T. the Extra-Terrestrial",1982,"Steven Spielberg",82,88,90,["alien","bicycle"],["blockbuster-core","kids-canon"]);
I("film-blockbuster","Jurassic Park",1993,"Steven Spielberg",90,92,94,["dinosaurs","awe"],["blockbuster-core"]);
I("film-blockbuster","Back to the Future",1985,"Robert Zemeckis",86,90,92,["time-travel","delorean"],["blockbuster-core","kids-canon"]);
I("film-blockbuster","The Terminator",1984,"James Cameron",74,84,86,["ai","time-travel"],["blockbuster-core","cyberpunk"]);
I("film-blockbuster","Terminator 2: Judgment Day",1991,"James Cameron",80,88,90,["liquid-metal","thumbs-up"],["blockbuster-core"]);
I("film-blockbuster","Aliens",1986,"James Cameron",68,86,88,["marines","queen"],["blockbuster-core","horror-canon"]);
I("film-blockbuster","Avatar",2009,"James Cameron",90,82,84,["pandora","3d"],["blockbuster-core"],[],"The brutality of colonialism is a shepherd tone.");
I("film-blockbuster","Avatar: The Way of Water",2022,"James Cameron",78,70,72,["pandora","ocean"],["blockbuster-core"],["avatar-2009"],"Watch the intentional frame-rate shifts — less motion blur than the first.");
I("film-blockbuster","Die Hard",1988,"John McTiernan",74,84,86,["tower","christmas"],["blockbuster-core"]);
I("film-blockbuster","The Matrix",1999,"The Wachowskis",88,94,96,["simulation","red-pill"],["blockbuster-core","cyberpunk","dorm-canon"],["neuromancer-1984"]);
I("film-blockbuster","The Lord of the Rings: The Fellowship of the Ring",2001,"Peter Jackson",88,92,95,["fantasy","fellowship"],["blockbuster-core","high-fantasy"],["the-lord-of-the-rings-1954","the-lord-of-the-rings-score-2001"]);
I("film-blockbuster","The Lord of the Rings: The Return of the King",2003,"Peter Jackson",86,92,95,["fantasy","ending"],["blockbuster-core","high-fantasy"]);
I("film-blockbuster","Harry Potter and the Philosopher's Stone",2001,"Chris Columbus",90,80,82,["wizards","school"],["blockbuster-core","kids-canon"],["harry-potter-series-1997"]);
I("film-blockbuster","Pirates of the Caribbean: The Curse of the Black Pearl",2003,"Gore Verbinski",82,74,76,["pirates","sparrow"],["blockbuster-core"]);
I("film-blockbuster","The Dark Knight",2008,"Christopher Nolan",90,92,94,["joker","chaos"],["blockbuster-core","dorm-canon"],["the-dark-knight-returns-1986"]);
I("film-blockbuster","Iron Man",2008,"Jon Favreau",84,84,86,["origin","mcu"],["blockbuster-core"]);
I("film-blockbuster","The Avengers",2012,"Joss Whedon",86,82,84,["team-up","mcu"],["blockbuster-core"]);
I("film-blockbuster","Avengers: Infinity War",2018,"Russo Brothers",86,80,82,["snap","mcu"],["blockbuster-core"]);
I("film-blockbuster","Avengers: Endgame",2019,"Russo Brothers",90,84,86,["time-heist","mcu"],["blockbuster-core"],["avengers-infinity-war-2018"]);
I("film-blockbuster","Black Panther",2018,"Ryan Coogler",80,82,84,["wakanda","mcu"],["blockbuster-core"]);
I("film-blockbuster","Spider-Man 2",2004,"Sam Raimi",72,78,80,["hero","train"],["blockbuster-core"]);
I("film-blockbuster","The Lion King",1994,"Allers & Minkoff",92,88,90,["hamlet","savanna"],["blockbuster-core","kids-canon","pixar-era"],["hamlet-1601","the-lion-king-1997"]);
I("film-blockbuster","Frozen",2013,"Buck & Lee",86,74,76,["sisters","let-it-go"],["kids-canon","blockbuster-core"]);
I("film-blockbuster","Top Gun: Maverick",2022,"Joseph Kosinski",76,72,74,["jets","legacy"],["blockbuster-core"]);
I("film-blockbuster","Mission: Impossible — Fallout",2018,"Christopher McQuarrie",64,70,72,["stunts","cruise"],["blockbuster-core"]);
I("film-blockbuster","John Wick",2014,"Chad Stahelski",68,72,74,["gun-fu","dog"],["blockbuster-core"]);
I("film-blockbuster","Gravity",2013,"Alfonso Cuarón",64,74,76,["orbit","debris"],["blockbuster-core","space-scifi"]);
I("film-blockbuster","The Martian",2015,"Ridley Scott",70,74,76,["mars","potatoes"],["blockbuster-core","space-scifi"],["the-martian-2011"]);
I("film-blockbuster","Dune",2021,"Denis Villeneuve",72,80,82,["desert","spice"],["blockbuster-core","space-scifi","visual-maximalism"],["dune-1965"]);
I("film-blockbuster","Barbie",2023,"Greta Gerwig",80,74,76,["pink","existential"],["blockbuster-core","meme-canon"],["oppenheimer-2023"],"One half of the last great shared cinema event.");
I("film-blockbuster","Rocky",1976,"John G. Avildsen",76,86,88,["boxing","underdog"],["blockbuster-core","fight-fans"]);
I("film-blockbuster","Speed Racer",2008,"The Wachowskis",30,50,58,["candy-colour","race"],["cult-canon","visual-maximalism"]);

/* ---- Film — World & Arthouse ---- */
I("film-world","Stalker",1979,"Andrei Tarkovsky",30,88,94,["zone","desire"],["criterion-core","arthouse"],[],"The Room grants your innermost wish — which is why nobody dares enter.");
I("film-world","Come and See",1985,"Elem Klimov",30,88,93,["war","belarus"],["criterion-core","wwii-memory","world-cinema"]);
I("film-world","In the Mood for Love",2000,"Wong Kar-wai",40,88,94,["longing","cheongsam"],["criterion-core","arthouse","world-cinema"]);
I("film-world","Chungking Express",1994,"Wong Kar-wai",36,82,88,["hong-kong","pineapple"],["criterion-core","arthouse"]);
I("film-world","Oldboy",2003,"Park Chan-wook",50,82,88,["revenge","hallway"],["world-cinema","cult-canon"]);
I("film-world","The Handmaiden",2016,"Park Chan-wook",42,78,84,["con","triple-cross"],["world-cinema","arthouse"]);
I("film-world","City of God",2002,"Fernando Meirelles",58,86,92,["favela","photography"],["world-cinema","film-buff"]);
I("film-world","Amélie",2001,"Jean-Pierre Jeunet",64,82,88,["whimsy","paris"],["world-cinema","arthouse"],["amelie-score-2001"]);
I("film-world","The City of Lost Children",1995,"Jeunet & Caro",26,62,72,["dreams","steampunk"],["visual-maximalism","cult-canon","world-cinema"]);
I("film-world","Pan's Labyrinth",2006,"Guillermo del Toro",62,86,92,["fairy-tale","fascism"],["world-cinema","visual-maximalism","high-fantasy"]);
I("film-world","Y Tu Mamá También",2001,"Alfonso Cuarón",38,74,80,["road-trip","mexico"],["world-cinema","arthouse"]);
I("film-world","Roma",2018,"Alfonso Cuarón",44,78,84,["memory","housekeeper"],["world-cinema","arthouse"]);
I("film-world","Amores Perros",2000,"Alejandro G. Iñárritu",36,74,80,["triptych","dogs"],["world-cinema"]);
I("film-world","A Separation",2011,"Asghar Farhadi",32,82,88,["divorce","iran"],["world-cinema","arthouse"]);
I("film-world","Life Is Beautiful",1997,"Roberto Benigni",66,80,82,["holocaust","game"],["world-cinema","wwii-memory"]);
I("film-world","Cinema Paradiso",1988,"Giuseppe Tornatore",48,82,86,["projectionist","kisses"],["world-cinema","film-buff"]);
I("film-world","Downfall",2004,"Oliver Hirschbiegel",50,76,80,["bunker","meme-source"],["world-cinema","wwii-memory","meme-canon"]);
I("film-world","The Lives of Others",2006,"F.H. von Donnersmarck",42,82,86,["stasi","surveillance"],["world-cinema","cold-war"]);
I("film-world","Run Lola Run",1998,"Tom Tykwer",38,70,76,["loops","berlin"],["world-cinema","cult-canon"],[],"Repeating the same day with different rng, hoping for a good outcome.");
I("film-world","Das Boot",1981,"Wolfgang Petersen",42,80,84,["u-boat","pressure"],["world-cinema","wwii-memory"]);
I("film-world","Hero",2002,"Zhang Yimou",44,76,82,["wuxia","colour-coded"],["world-cinema","visual-maximalism"]);
I("film-world","Crouching Tiger, Hidden Dragon",2000,"Ang Lee",58,80,84,["wuxia","bamboo"],["world-cinema"]);
I("film-world","Mulholland Drive",2001,"David Lynch",42,86,92,["dream-logic","hollywood"],["arthouse","cult-canon"]);
I("film-world","Blue Velvet",1986,"David Lynch",38,82,88,["suburbia","underworld"],["arthouse","cult-canon"]);
I("film-world","Eraserhead",1977,"David Lynch",28,74,82,["industrial","baby"],["cult-canon","arthouse"]);
I("film-world","The Tree of Life",2011,"Terrence Malick",32,74,82,["creation","memory"],["arthouse","visual-maximalism"]);
I("film-world","Paris, Texas",1984,"Wim Wenders",30,80,86,["desert","estrangement"],["criterion-core","arthouse"]);
I("film-world","Portrait of a Lady on Fire",2019,"Céline Sciamma",40,78,84,["gaze","portrait"],["arthouse","world-cinema"]);
I("film-world","Ikiru",1952,"Akira Kurosawa",26,84,90,["mortality","swing"],["criterion-core","world-cinema"]);
I("film-world","Yi Yi",2000,"Edward Yang",22,82,88,["family","taipei"],["criterion-core","world-cinema"]);

/* ---- Film — Horror ---- */
I("film-horror","The Exorcist",1973,"William Friedkin",72,90,94,["possession","faith"],["horror-canon"]);
I("film-horror","Halloween",1978,"John Carpenter",68,86,90,["slasher","mask"],["horror-canon"]);
I("film-horror","The Texas Chain Saw Massacre",1974,"Tobe Hooper",56,82,86,["slasher","leatherface"],["horror-canon","cult-canon"]);
I("film-horror","A Nightmare on Elm Street",1984,"Wes Craven",64,80,84,["dreams","freddy"],["horror-canon"]);
I("film-horror","Scream",1996,"Wes Craven",68,80,84,["meta","ghostface"],["horror-canon"]);
I("film-horror","The Thing",1982,"John Carpenter",56,84,90,["paranoia","antarctic"],["horror-canon","cult-canon"]);
I("film-horror","Alien",1979,"Ridley Scott",76,92,95,["xenomorph","space"],["horror-canon","space-scifi","blockbuster-core"]);
I("film-horror","Rosemary's Baby",1968,"Roman Polanski",48,84,88,["paranoia","cult"],["horror-canon"]);
I("film-horror","Night of the Living Dead",1968,"George A. Romero",54,86,90,["zombies","first"],["horror-canon","cult-canon"]);
I("film-horror","28 Days Later",2002,"Danny Boyle",56,76,80,["rage","empty-london"],["horror-canon"]);
I("film-horror","The Ring",2002,"Gore Verbinski",62,72,76,["tape","seven-days"],["horror-canon"]);
I("film-horror","The Blair Witch Project",1999,"Myrick & Sánchez",60,80,84,["found-footage","woods"],["horror-canon"]);
I("film-horror","Paranormal Activity",2007,"Oren Peli",58,66,70,["found-footage","bedroom"],["horror-canon"]);
I("film-horror","Saw",2004,"James Wan",64,70,74,["trap","games"],["horror-canon"]);
I("film-horror","The Conjuring",2013,"James Wan",66,68,72,["haunting","warrens"],["horror-canon"]);
I("film-horror","It Follows",2014,"David Robert Mitchell",42,68,76,["curse","walking"],["horror-canon","a24-wave"]);
I("film-horror","The Witch",2015,"Robert Eggers",44,72,80,["puritan","goat"],["horror-canon","a24-wave"]);
I("film-horror","Hereditary",2018,"Ari Aster",54,78,84,["family","dread"],["horror-canon","a24-wave"]);
I("film-horror","Midsommar",2019,"Ari Aster",52,72,78,["daylight","cult"],["horror-canon","a24-wave"]);
I("film-horror","Suspiria",1977,"Dario Argento",34,74,82,["giallo","colour"],["horror-canon","cult-canon","visual-maximalism"]);

/* ---- Film — Cult & Midnight ---- */
I("film-cult","The Rocky Horror Picture Show",1975,"Jim Sharman",52,76,86,["midnight","audience"],["cult-canon","musical-theatre"]);
I("film-cult","Monty Python and the Holy Grail",1975,"Gilliam & Jones",68,86,92,["comedy","coconuts"],["cult-canon","brit-comedy","dorm-canon"]);
I("film-cult","Monty Python's Life of Brian",1979,"Terry Jones",56,82,86,["satire","blessed"],["cult-canon","brit-comedy"]);
I("film-cult","This Is Spinal Tap",1984,"Rob Reiner",44,80,86,["mockumentary","eleven"],["cult-canon","classic-rock"]);
I("film-cult","The Princess Bride",1987,"Rob Reiner",66,84,90,["frame-story","fencing"],["cult-canon","kids-canon","high-fantasy"],[],"A story read to a sick child — the gentlest of the nested-tale films.");
I("film-cult","Labyrinth",1986,"Jim Henson",52,70,78,["goblin-king","puppets"],["cult-canon","kids-canon"],["the-rise-and-fall-of-ziggy-stardust-1972"]);
I("film-cult","Highlander",1986,"Russell Mulcahy",46,64,74,["immortals","quickening"],["cult-canon"],[],"There can be only one.");
I("film-cult","The Lost Boys",1987,"Joel Schumacher",42,60,72,["vampires","boardwalk"],["cult-canon","horror-canon"],["dracula-1897"],"Santa Carla, saxophone man, the cool undead.");
I("film-cult","Evil Dead II",1987,"Sam Raimi",42,70,80,["splatstick","groovy"],["cult-canon","horror-canon"]);
I("film-cult","Shaun of the Dead",2004,"Edgar Wright",58,76,82,["zomcom","winchester"],["cult-canon","brit-comedy","horror-canon"]);
I("film-cult","Hot Fuzz",2007,"Edgar Wright",54,74,80,["cops","village"],["cult-canon","brit-comedy"]);
I("film-cult","Scott Pilgrim vs. the World",2010,"Edgar Wright",50,68,76,["videogame","exes"],["cult-canon","gamer-core"]);
I("film-cult","Office Space",1999,"Mike Judge",48,70,78,["cubicle","printer"],["cult-canon","meme-canon"]);
I("film-cult","The Room",2003,"Tommy Wiseau",38,58,74,["so-bad","spoons"],["cult-canon","meme-canon"]);
I("film-cult","Ferris Bueller's Day Off",1986,"John Hughes",66,78,82,["truancy","fourth-wall"],["cult-canon","kids-canon"]);
I("film-cult","The Breakfast Club",1985,"John Hughes",68,80,84,["detention","archetypes"],["cult-canon","dorm-canon"]);
I("film-cult","Heathers",1988,"Michael Lehmann",40,66,76,["dark-comedy","cliques"],["cult-canon"]);
I("film-cult","Clueless",1995,"Amy Heckerling",60,72,78,["austen","valley"],["cult-canon"]);
I("film-cult","Mean Girls",2004,"Mark Waters",72,74,80,["cliques","quotable"],["cult-canon","meme-canon"]);
I("film-cult","Napoleon Dynamite",2004,"Jared Hess",50,62,72,["deadpan","dance"],["cult-canon"]);
I("film-cult","Brazil",1985,"Terry Gilliam",36,78,84,["bureaucracy","ducts"],["cult-canon","dystopia-canon"]);
I("film-cult","Koyaanisqatsi",1982,"Godfrey Reggio",26,72,82,["wordless","timelapse"],["visual-maximalism","arthouse"],["glassworks-1982"],"Life out of balance — the frame-rate as argument.");

/* ---- Animated Features ---- */
I("animation-film","Snow White and the Seven Dwarfs",1937,"Walt Disney",76,92,94,["first","fairy-tale"],["kids-canon"]);
I("animation-film","Fantasia",1940,"Walt Disney",56,84,86,["music","abstract"],["kids-canon","classical-core"]);
I("animation-film","Aladdin",1992,"Clements & Musker",84,78,80,["genie","wishes"],["kids-canon"]);
I("animation-film","Beauty and the Beast",1991,"Trousdale & Wise",80,82,84,["tale-as-old"],["kids-canon"]);
I("animation-film","Toy Story",1995,"John Lasseter",90,92,95,["first-cg","toys"],["pixar-era","kids-canon"]);
I("animation-film","Toy Story 3",2010,"Lee Unkrich",78,80,82,["letting-go","incinerator"],["pixar-era","kids-canon"]);
I("animation-film","Finding Nemo",2003,"Andrew Stanton",86,82,84,["ocean","p-sherman"],["pixar-era","kids-canon"]);
I("animation-film","WALL-E",2008,"Andrew Stanton",74,86,90,["robot","waste"],["pixar-era","space-scifi"]);
I("animation-film","Up",2009,"Pete Docter",80,82,86,["balloons","married-life"],["pixar-era","kids-canon"]);
I("animation-film","Inside Out",2015,"Pete Docter",76,80,84,["emotions","hq"],["pixar-era","kids-canon"]);
I("animation-film","Coco",2017,"Lee Unkrich",74,78,82,["memory","dia-de-muertos"],["pixar-era","kids-canon"]);
I("animation-film","Ratatouille",2007,"Brad Bird",76,80,84,["cooking","critic"],["pixar-era"]);
I("animation-film","The Incredibles",2004,"Brad Bird",80,80,82,["family","supers"],["pixar-era","kids-canon"]);
I("animation-film","Shrek",2001,"Adamson & Jenson",88,80,82,["ogre","fairy-tale-satire"],["kids-canon","meme-canon"]);
I("animation-film","How to Train Your Dragon",2010,"DeBlois & Sanders",72,72,76,["dragon","flight"],["kids-canon"]);
I("animation-film","The Nightmare Before Christmas",1993,"Henry Selick",62,74,80,["stop-motion","holidays"],["cult-canon","kids-canon"]);
I("animation-film","Wallace & Gromit: The Wrong Trousers",1993,"Nick Park",54,76,84,["claymation","penguin"],["brit-comedy","kids-canon"]);
I("animation-film","Spider-Man: Into the Spider-Verse",2018,"Persichetti, Ramsey, Rothman",72,84,90,["multiverse","style"],["kids-canon","comics-canon","visual-maximalism"]);

/* ---- Anime — Films ---- */
I("anime-film","My Neighbor Totoro",1988,"Hayao Miyazaki",68,86,90,["childhood","forest"],["ghibli","kids-canon"]);
I("anime-film","Spirited Away",2001,"Hayao Miyazaki",78,94,98,["bathhouse","names"],["ghibli","anime-gateway","world-cinema"]);
I("anime-film","Princess Mononoke",1997,"Hayao Miyazaki",60,88,92,["forest-gods","industry"],["ghibli","anime-deep"]);
I("anime-film","Howl's Moving Castle",2004,"Hayao Miyazaki",66,82,86,["castle","curse"],["ghibli","anime-gateway"]);
I("anime-film","Kiki's Delivery Service",1989,"Hayao Miyazaki",56,78,82,["witch","independence"],["ghibli","kids-canon"]);
I("anime-film","Grave of the Fireflies",1988,"Isao Takahata",44,86,90,["war","siblings"],["ghibli","wwii-memory"]);
I("anime-film","Akira",1988,"Katsuhiro Otomo",54,90,94,["neo-tokyo","bike-slide"],["anime-deep","cyberpunk"],["akira-1982"]);
I("anime-film","Ghost in the Shell",1995,"Mamoru Oshii",46,84,90,["cyborg","identity"],["anime-deep","cyberpunk"],["the-matrix-1999"]);
I("anime-film","Perfect Blue",1997,"Satoshi Kon",36,78,86,["identity","idol"],["anime-deep"],["black-swan-2010"]);
I("anime-film","Paprika",2006,"Satoshi Kon",38,76,84,["dreams","parade"],["anime-deep","visual-maximalism"],["inception-2010"]);
I("anime-film","Your Name",2016,"Makoto Shinkai",66,80,86,["body-swap","comet"],["anime-gateway"]);
I("anime-film","A Silent Voice",2016,"Naoko Yamada",50,72,80,["bullying","redemption"],["anime-gateway"]);
I("anime-film","The End of Evangelion",1997,"Hideaki Anno",38,80,88,["instrumentality","ending"],["anime-deep"],["neon-genesis-evangelion-1995"]);

/* ---- Documentary ---- */
I("documentary","Life on Earth",1979,"David Attenborough",48,88,92,["nature","survey"],["nature-docs"]);
I("documentary","Planet Earth",2006,"BBC / David Attenborough",76,88,94,["nature","hd"],["nature-docs"]);
I("documentary","Blue Planet II",2017,"BBC / David Attenborough",64,82,86,["ocean","plastic"],["nature-docs"]);
I("documentary","Cosmos: A Personal Voyage",1980,"Carl Sagan",50,88,92,["universe","sagan"],["nature-docs","space-race","big-ideas"],["cosmos-1980"]);
I("documentary","My Octopus Teacher",2020,"Ehrlich & Reed",52,64,70,["kelp","bond"],["nature-docs"]);
I("documentary","Free Solo",2018,"Chin & Vasarhelyi",56,72,80,["climbing","el-cap"],["sports-docs"]);
I("documentary","Senna",2010,"Asif Kapadia",42,74,84,["f1","genius"],["sports-docs","f1-fandom"],["death-of-ayrton-senna-imola-1994"]);
I("documentary","The Last Dance",2020,"Jason Hehir",62,74,84,["jordan","bulls"],["sports-docs","hoops"],["the-last-shot-1998"]);
I("documentary","Hoop Dreams",1994,"Steve James",34,80,88,["chicago","longitudinal"],["sports-docs","hoops"]);
I("documentary","Icarus",2017,"Bryan Fogel",40,66,74,["doping","russia"],["sports-docs","true-crime"]);
I("documentary","Man on Wire",2008,"James Marsh",38,72,80,["wire-walk","towers"],["film-buff"],["world-trade-center-twin-towers-1973"]);
I("documentary","Grizzly Man",2005,"Werner Herzog",36,72,82,["bears","hubris"],["arthouse","nature-docs"]);
I("documentary","The Act of Killing",2012,"Joshua Oppenheimer",28,80,88,["perpetrators","reenactment"],["arthouse","true-crime"]);
I("documentary","The Thin Blue Line",1988,"Errol Morris",26,76,86,["wrongful-conviction","reenactment"],["true-crime"]);
I("documentary","Making a Murderer",2015,"Ricciardi & Demos",56,60,68,["conviction","binge"],["true-crime"]);
I("documentary","Tiger King",2020,"Goode & Chaiklin",68,50,56,["lockdown","chaos"],["true-crime","meme-canon"],["covid-19-pandemic-2020"]);
I("documentary","Searching for Sugar Man",2012,"Malik Bendjelloul",36,66,76,["rodriguez","mystery"],["film-buff","folk-canon"]);
I("documentary","Bowling for Columbine",2002,"Michael Moore",46,68,74,["guns","america"],["big-ideas"]);
I("documentary","An Inconvenient Truth",2006,"Davis Guggenheim",52,72,76,["climate","slideshow"],["big-ideas"]);
I("documentary","Super Size Me",2004,"Morgan Spurlock",52,60,66,["fast-food","stunt"],["big-ideas"]);
I("documentary","Baraka",1992,"Ron Fricke",24,66,80,["wordless","planet"],["visual-maximalism","arthouse"],["koyaanisqatsi-1982"],"Ninety minutes of the earth breathing, no words permitted.");
I("documentary","Samsara",2011,"Ron Fricke",22,62,76,["wordless","cycles"],["visual-maximalism","arthouse"],["baraka-1992"]);
I("documentary","Won't You Be My Neighbor?",2018,"Morgan Neville",38,62,70,["rogers","kindness"],["film-buff"]);
I("documentary","13th",2016,"Ava DuVernay",42,72,78,["prison","amendment"],["big-ideas"]);
I("documentary","March of the Penguins",2005,"Luc Jacquet",54,62,68,["antarctic","journey"],["nature-docs"]);

/* ---- Television — Drama ---- */
I("tv-drama","The Sopranos",1999,"David Chase",70,94,98,["mob","therapy"],["prestige-tv"]);
I("tv-drama","The Wire",2002,"David Simon",56,94,98,["baltimore","institutions"],["prestige-tv"]);
I("tv-drama","Breaking Bad",2008,"Vince Gilligan",88,94,98,["meth","transformation"],["prestige-tv","dorm-canon"]);
I("tv-drama","Better Call Saul",2015,"Gilligan & Gould",64,84,90,["prequel","slippin"],["prestige-tv"],["breaking-bad-2008"]);
I("tv-drama","Mad Men",2007,"Matthew Weiner",56,88,93,["advertising","identity"],["prestige-tv"]);
I("tv-drama","Game of Thrones",2011,"Benioff & Weiss",92,88,92,["fantasy","thrones"],["prestige-tv","high-fantasy"],["a-game-of-thrones-1996"]);
I("tv-drama","Succession",2018,"Jesse Armstrong",58,84,90,["media-empire","siblings"],["prestige-tv","brit-comedy"]);
I("tv-drama","Severance",2022,"Dan Erickson",56,76,84,["work-self","innie"],["prestige-tv","dystopia-canon"]);
I("tv-drama","The Leftovers",2014,"Lindelof & Perrotta",36,78,88,["departure","grief"],["prestige-tv"]);
I("tv-drama","Lost",2004,"Abrams & Lindelof",78,80,84,["island","mystery-box"],["prestige-tv"]);
I("tv-drama","Twin Peaks",1990,"Lynch & Frost",52,88,93,["owls","lodge"],["prestige-tv","cult-canon","arthouse"]);
I("tv-drama","The X-Files",1993,"Chris Carter",68,82,85,["aliens","believe"],["prestige-tv","cult-canon"]);
I("tv-drama","Buffy the Vampire Slayer",1997,"Joss Whedon",58,80,84,["slayer","hellmouth"],["cult-canon"]);
I("tv-drama","Doctor Who",1963,"BBC",72,86,90,["tardis","regeneration"],["brit-comedy","sff-canon"]);
I("tv-drama","Sherlock",2010,"Moffat & Gatiss",74,74,78,["deduction","modern"],["prestige-tv","brit-comedy"],["the-adventures-of-sherlock-holmes-1892"]);
I("tv-drama","True Detective",2014,"Nic Pizzolatto",58,80,86,["time-flat-circle","carcosa"],["prestige-tv","crime-noir"]);
I("tv-drama","Fargo",2014,"Noah Hawley",44,76,82,["anthology","snow"],["prestige-tv","crime-noir"]);
I("tv-drama","Westworld",2016,"Nolan & Joy",56,70,74,["hosts","maze"],["prestige-tv","cyberpunk"]);
I("tv-drama","Stranger Things",2016,"Duffer Brothers",84,74,78,["upside-down","80s"],["prestige-tv","kids-canon"]);
I("tv-drama","Black Mirror",2011,"Charlie Brooker",74,84,88,["anthology","tech-dread"],["prestige-tv","dystopia-canon","internet-native"]);
I("tv-drama","Chernobyl",2019,"Craig Mazin",62,84,90,["cost-of-lies","graphite"],["prestige-tv"],["chernobyl-disaster-1986"]);
I("tv-drama","Band of Brothers",2001,"Spielberg & Hanks",64,86,90,["easy-company","ww2"],["prestige-tv","wwii-memory"],["d-day-the-normandy-landings-1944"]);
I("tv-drama","The Crown",2016,"Peter Morgan",62,72,76,["monarchy","decades"],["prestige-tv"],["princess-dianas-funeral-1997"]);
I("tv-drama","Downton Abbey",2010,"Julian Fellowes",64,68,72,["estate","upstairs-downstairs"],["prestige-tv"]);
I("tv-drama","Peaky Blinders",2013,"Steven Knight",66,68,74,["birmingham","caps"],["prestige-tv"]);
I("tv-drama","Narcos",2015,"Chris Brancato",62,64,70,["escobar","dea"],["prestige-tv","true-crime"]);
I("tv-drama","Money Heist",2017,"Álex Pina",68,58,64,["heist","dali-masks"],["prestige-tv"]);
I("tv-drama","Squid Game",2021,"Hwang Dong-hyuk",84,74,78,["debt","games"],["prestige-tv","dystopia-canon"]);
I("tv-drama","Dark",2017,"bo Odar & Friese",48,74,82,["time-knot","winden"],["prestige-tv","sff-canon"]);
I("tv-drama","Mr. Robot",2015,"Sam Esmail",52,72,78,["hacker","fsociety"],["prestige-tv","cyberpunk","dorm-canon"]);
I("tv-drama","Legion",2017,"Noah Hawley",30,60,72,["unreliable-mind","mutant"],["prestige-tv","cult-canon","visual-maximalism"],[],"Television that renders the inside of a mind — the astral plane as production design.");
I("tv-drama","Dexter",2006,"James Manos Jr.",64,60,64,["serial-killer","code"],["prestige-tv"]);
I("tv-drama","House",2004,"David Shore",76,68,72,["diagnosis","lupus"],["prestige-tv"]);
I("tv-drama","24",2001,"Surnow & Cochran",64,62,66,["real-time","ctu"],["prestige-tv"]);
I("tv-drama","Prison Break",2005,"Paul Scheuring",66,54,58,["tattoo","escape"],[]);
I("tv-drama","Grey's Anatomy",2005,"Shonda Rhimes",76,58,62,["hospital","longevity"],["sitcom-comfort"]);
I("tv-drama","The Mandalorian",2019,"Jon Favreau",70,64,68,["grogu","bounty"],["blockbuster-core","sff-canon"],["star-wars-a-new-hope-1977"]);
I("tv-drama","Andor",2022,"Tony Gilroy",44,70,78,["rebellion","spy"],["prestige-tv","sff-canon"]);
I("tv-drama","The Last of Us",2023,"Mazin & Druckmann",66,72,76,["cordyceps","father-daughter"],["prestige-tv"],["the-last-of-us-2013"]);
I("tv-drama","The Bear",2022,"Christopher Storer",58,72,78,["kitchen","yes-chef"],["prestige-tv"]);
I("tv-drama","The White Lotus",2021,"Mike White",56,68,74,["resort","class"],["prestige-tv"]);
I("tv-drama","Avatar: The Last Airbender",2005,"DiMartino & Konietzko",70,82,88,["elements","redemption-arc"],["kids-canon","anime-gateway"]);
I("tv-drama","The Twilight Zone",1959,"Rod Serling",60,90,94,["anthology","twist"],["cult-canon","sff-canon"]);

/* ---- Television — Comedy & Animation ---- */
I("tv-comedy","I Love Lucy",1951,"CBS",56,88,90,["first-sitcom","chocolate-line"],["sitcom-comfort"]);
I("tv-comedy","M*A*S*H",1972,"Larry Gelbart",58,84,86,["war","finale"],["sitcom-comfort"],["m-a-s-h-finale-1983"]);
I("tv-comedy","Cheers",1982,"Burrows & Charles",60,80,84,["bar","norm"],["sitcom-comfort"]);
I("tv-comedy","Frasier",1993,"Angell, Casey, Lee",56,74,80,["seattle","brothers"],["sitcom-comfort"]);
I("tv-comedy","Seinfeld",1989,"David & Seinfeld",78,92,96,["nothing","observational"],["sitcom-comfort"]);
I("tv-comedy","Friends",1994,"Crane & Kauffman",92,84,88,["six-friends","central-perk"],["sitcom-comfort"]);
I("tv-comedy","The Office (UK)",2001,"Gervais & Merchant",48,80,88,["mockumentary","brent"],["brit-comedy","sitcom-comfort"]);
I("tv-comedy","The Office (US)",2005,"Greg Daniels",88,84,90,["mockumentary","dunder-mifflin"],["sitcom-comfort","meme-canon"],["the-office-uk-2001"]);
I("tv-comedy","Parks and Recreation",2009,"Daniels & Schur",68,74,80,["pawnee","optimism"],["sitcom-comfort"]);
I("tv-comedy","30 Rock",2006,"Tina Fey",52,74,80,["show-within-show","liz-lemon"],["sitcom-comfort"]);
I("tv-comedy","Community",2009,"Dan Harmon",54,72,80,["meta","paintball"],["sitcom-comfort","cult-canon"]);
I("tv-comedy","Arrested Development",2003,"Mitchell Hurwitz",56,76,84,["banana-stand","narrator"],["sitcom-comfort","cult-canon"]);
I("tv-comedy","It's Always Sunny in Philadelphia",2005,"Rob McElhenney",62,70,78,["gang","depravity"],["sitcom-comfort","cult-canon"]);
I("tv-comedy","Curb Your Enthusiasm",2000,"Larry David",56,76,82,["improv","pretty-good"],["sitcom-comfort"]);
I("tv-comedy","How I Met Your Mother",2005,"Bays & Thomas",78,66,70,["frame-story","yellow-umbrella"],["sitcom-comfort"]);
I("tv-comedy","The Big Bang Theory",2007,"Lorre & Prady",82,60,64,["nerds","bazinga"],["sitcom-comfort"]);
I("tv-comedy","Modern Family",2009,"Levitan & Lloyd",74,64,68,["mockumentary","family"],["sitcom-comfort"]);
I("tv-comedy","Brooklyn Nine-Nine",2013,"Goor & Schur",68,62,68,["precinct","cool-cool"],["sitcom-comfort"]);
I("tv-comedy","Schitt's Creek",2015,"Dan & Eugene Levy",60,64,70,["riches-to-rags","ew-david"],["sitcom-comfort"]);
I("tv-comedy","Ted Lasso",2020,"Sudeikis & Lawrence",62,66,72,["believe","football"],["sitcom-comfort","football-global"]);
I("tv-comedy","Veep",2012,"Armando Iannucci",44,72,80,["politics","insults"],["brit-comedy","prestige-tv"]);
I("tv-comedy","The Thick of It",2005,"Armando Iannucci",34,72,82,["spin","tucker"],["brit-comedy"]);
I("tv-comedy","Fawlty Towers",1975,"Cleese & Booth",52,84,90,["hotel","basil"],["brit-comedy","sitcom-comfort"]);
I("tv-comedy","Monty Python's Flying Circus",1969,"Monty Python",58,90,94,["sketch","absurd"],["brit-comedy","cult-canon"]);
I("tv-comedy","Blackadder",1983,"Curtis & Atkinson",50,78,86,["history","cunning-plan"],["brit-comedy"]);
I("tv-comedy","Mr. Bean",1990,"Rowan Atkinson",84,72,76,["silent","turkey"],["brit-comedy","kids-canon"]);
I("tv-comedy","Peep Show",2003,"Bain & Armstrong",42,70,82,["pov","el-dude-brothers"],["brit-comedy"]);
I("tv-comedy","The IT Crowd",2006,"Graham Linehan",50,66,74,["basement","turn-it-off-and-on"],["brit-comedy","meme-canon"]);
I("tv-comedy","The Inbetweeners",2008,"Beesley & Morris",52,62,72,["sixth-form","cringe"],["brit-comedy"]);
I("tv-comedy","Fleabag",2016,"Phoebe Waller-Bridge",56,78,86,["fourth-wall","hot-priest"],["brit-comedy","prestige-tv"]);
I("tv-comedy","Derry Girls",2018,"Lisa McGee",46,64,72,["troubles","school"],["brit-comedy"]);
I("tv-comedy","The Simpsons",1989,"Matt Groening",92,94,98,["springfield","satire"],["adult-animation","kids-canon","meme-canon"]);
I("tv-comedy","Futurama",1999,"Groening & Cohen",64,76,84,["year-3000","good-news"],["adult-animation","cult-canon"],[],"S4's 'Godfellas' — God-as-drifting-computation — is twenty-two minutes of theology better than most books manage.");
I("tv-comedy","South Park",1997,"Parker & Stone",78,80,84,["satire","construction-paper"],["adult-animation"]);
I("tv-comedy","Family Guy",1999,"Seth MacFarlane",80,66,70,["cutaways","quahog"],["adult-animation"]);
I("tv-comedy","Rick and Morty",2013,"Roiland & Harmon",76,72,78,["multiverse","nihilism"],["adult-animation","dorm-canon"]);
I("tv-comedy","BoJack Horseman",2014,"Raphael Bob-Waksberg",56,76,84,["depression","hollywoo"],["adult-animation","prestige-tv"]);
I("tv-comedy","Archer",2009,"Adam Reed",50,60,66,["spy","phrasing"],["adult-animation"]);
I("tv-comedy","King of the Hill",1997,"Judge & Daniels",54,66,72,["propane","texas"],["adult-animation"]);
I("tv-comedy","SpongeBob SquarePants",1999,"Stephen Hillenburg",90,78,82,["bikini-bottom","optimism"],["kids-canon","meme-canon"]);
I("tv-comedy","Adventure Time",2010,"Pendleton Ward",58,72,80,["ooo","algebraic"],["kids-canon","cult-canon"]);
I("tv-comedy","Gravity Falls",2012,"Alex Hirsch",54,66,76,["mystery","ciphers"],["kids-canon","cult-canon"]);
I("tv-comedy","Saturday Night Live",1975,"Lorne Michaels",78,86,88,["sketch","live"],["broadcast-lore"]);

/* ---- Anime — Series ---- */
I("anime-tv","Neon Genesis Evangelion",1995,"Hideaki Anno",50,88,94,["mecha","psyche"],["anime-deep"],["the-end-of-evangelion-1997"]);
I("anime-tv","Cowboy Bebop",1998,"Shinichirō Watanabe",52,86,92,["bounty","jazz"],["anime-deep"],["kind-of-blue-1959"]);
I("anime-tv","Dragon Ball Z",1989,"Toei Animation",84,84,90,["power-levels","kamehameha"],["anime-gateway","kids-canon"],["dragon-ball-1984"]);
I("anime-tv","Pokémon",1997,"OLM",88,80,84,["gotta-catch","ash"],["anime-gateway","kids-canon"],["pokemon-red-and-blue-1996"]);
I("anime-tv","Sailor Moon",1992,"Toei Animation",64,74,80,["magical-girl","moon-prism"],["anime-gateway"]);
I("anime-tv","Death Note",2006,"Madhouse",72,80,88,["notebook","cat-mouse"],["anime-gateway"]);
I("anime-tv","Fullmetal Alchemist: Brotherhood",2009,"Bones",64,82,90,["equivalent-exchange","brothers"],["anime-gateway"]);
I("anime-tv","Attack on Titan",2013,"Wit / MAPPA",76,80,86,["walls","basement"],["anime-gateway"],["attack-on-titan-2009"]);
I("anime-tv","Hunter x Hunter",2011,"Madhouse",54,74,84,["nen","chimera-ant"],["anime-deep","anime-gateway"]);
I("anime-tv","Steins;Gate",2011,"White Fox",44,72,82,["time-travel","microwave"],["anime-deep"]);
I("anime-tv","Code Geass",2006,"Sunrise",48,68,78,["geass","zero"],["anime-gateway"]);
I("anime-tv","One-Punch Man",2015,"Madhouse",66,64,72,["parody","one-punch"],["anime-gateway"]);
I("anime-tv","Demon Slayer",2019,"ufotable",74,66,74,["breathing","animation-flex"],["anime-gateway"]);
I("anime-tv","Jujutsu Kaisen",2020,"MAPPA",70,62,70,["curses","domain"],["anime-gateway"]);
I("anime-tv","My Hero Academia",2016,"Bones",66,60,68,["quirks","plus-ultra"],["anime-gateway"]);
I("anime-tv","Sword Art Online",2012,"A-1 Pictures",62,54,60,["vrmmo","trapped"],["anime-gateway","gamer-core"]);

/* ---- Shorts & Music Video ---- */
I("shorts-mv","Un Chien Andalou",1929,"Buñuel & Dalí",22,78,88,["surreal","eye"],["arthouse","modern-art"],["the-persistence-of-memory-1931"]);
I("shorts-mv","La Jetée",1962,"Chris Marker",18,74,86,["photo-roman","time"],["arthouse","criterion-core"]);
I("shorts-mv","Thriller",1983,"Michael Jackson / John Landis",88,90,96,["music-video","zombies"],["pop-core","broadcast-lore"],["thriller-1982"]);
I("shorts-mv","Take On Me",1985,"a-ha / Steve Barron",76,74,84,["rotoscope","sketch"],["pop-core","meme-canon"]);
I("shorts-mv","Sledgehammer",1986,"Peter Gabriel / Stephen R. Johnson",44,70,82,["stop-motion","mtv"],["classic-rock"]);
I("shorts-mv","This Is America",2018,"Childish Gambino / Hiro Murai",62,76,86,["choreography","commentary"],["hiphop-modern","meme-canon"]);
I("shorts-mv","Vessel (OK Go — Here It Goes Again)",2006,"OK Go",48,58,72,["treadmills","one-take"],["viral-era"]);
