/* The Written Word */
"use strict";

/* ---- Myth, Epic & Scripture ---- */
I("myth-epic","The Epic of Gilgamesh",-2100,"",48,92,96,["epic","myth","mortality"],["canon-west","lit-canon"]);
I("myth-epic","The Iliad",-750,"Homer",68,96,99,["epic","war","myth"],["canon-west","lit-canon"]);
I("myth-epic","The Odyssey",-725,"Homer",78,96,100,["epic","journey","myth"],["canon-west","lit-canon"]);
I("myth-epic","The Bible",100,"",99,100,100,["scripture","myth","law"],["canon-west"]);
I("myth-epic","The Quran",650,"",96,99,99,["scripture","law"],[]);
I("myth-epic","The Mahabharata",-400,"Vyasa",72,95,98,["epic","war","dharma"],[]);
I("myth-epic","The Ramayana",-500,"Valmiki",68,92,95,["epic","journey"],[]);
I("myth-epic","The Aeneid",-19,"Virgil",46,88,92,["epic","founding"],["canon-west","lit-canon"]);
I("myth-epic","Metamorphoses",8,"Ovid",38,85,88,["myth","transformation"],["canon-west","lit-canon"]);
I("myth-epic","Beowulf",900,"",52,82,86,["epic","monster"],["canon-west","lit-canon"]);
I("myth-epic","The Poetic Edda",1270,"",34,80,84,["myth","norse"],["canon-west"]);
I("myth-epic","One Thousand and One Nights",900,"",70,90,93,["frame-story","tales"],["canon-west"],["the-fall-2006"],"The ur-nested-story — everything with a storyteller inside it descends from here.");
I("myth-epic","Journey to the West",1592,"Wu Cheng'en",64,90,94,["epic","journey","monkey"],[],["dragon-ball-1984"]);
I("myth-epic","The Divine Comedy",1320,"Dante Alighieri",62,95,98,["epic","afterlife"],["canon-west","lit-canon"]);
I("myth-epic","Paradise Lost",1667,"John Milton",44,88,90,["epic","fall"],["canon-west","poetry-canon"]);

/* ---- Classic Novels ---- */
I("classic-novel","Don Quixote",1605,"Miguel de Cervantes",66,97,100,["satire","quest"],["canon-west","lit-canon"]);
I("classic-novel","Pride and Prejudice",1813,"Jane Austen",84,90,97,["romance","manners"],["canon-west","lit-canon"]);
I("classic-novel","Jane Eyre",1847,"Charlotte Brontë",70,84,90,["gothic","romance"],["canon-west","lit-canon"]);
I("classic-novel","Wuthering Heights",1847,"Emily Brontë",68,83,89,["gothic","obsession"],["canon-west","lit-canon"]);
I("classic-novel","Moby-Dick",1851,"Herman Melville",72,93,97,["obsession","sea"],["canon-west","lit-canon"]);
I("classic-novel","Great Expectations",1861,"Charles Dickens",66,85,90,["coming-of-age"],["canon-west","lit-canon"]);
I("classic-novel","A Tale of Two Cities",1859,"Charles Dickens",70,86,90,["revolution"],["canon-west","lit-canon"]);
I("classic-novel","Crime and Punishment",1866,"Fyodor Dostoevsky",74,93,97,["guilt","crime"],["canon-west","lit-canon","russian-lit","dorm-canon"]);
I("classic-novel","The Brothers Karamazov",1880,"Fyodor Dostoevsky",58,94,97,["faith","family"],["canon-west","lit-canon","russian-lit"]);
I("classic-novel","War and Peace",1869,"Leo Tolstoy",66,96,99,["war","epic"],["canon-west","lit-canon","russian-lit"]);
I("classic-novel","Anna Karenina",1878,"Leo Tolstoy",64,92,95,["romance","tragedy"],["canon-west","lit-canon","russian-lit"]);
I("classic-novel","Madame Bovary",1857,"Gustave Flaubert",50,88,92,["realism","desire"],["canon-west","lit-canon"]);
I("classic-novel","Les Misérables",1862,"Victor Hugo",76,90,93,["justice","epic"],["canon-west","lit-canon"],["les-miserables-1985"]);
I("classic-novel","The Count of Monte Cristo",1844,"Alexandre Dumas",74,84,89,["revenge","adventure"],["canon-west","lit-canon"]);
I("classic-novel","Adventures of Huckleberry Finn",1884,"Mark Twain",70,88,93,["river","satire"],["canon-west","lit-canon"]);
I("classic-novel","Frankenstein",1818,"Mary Shelley",82,93,96,["gothic","creation","scifi"],["canon-west","lit-canon","sff-canon"]);
I("classic-novel","Dracula",1897,"Bram Stoker",80,88,92,["gothic","vampire"],["canon-west","horror-canon"],["the-lost-boys-1987"]);
I("classic-novel","The Picture of Dorian Gray",1890,"Oscar Wilde",66,84,88,["gothic","vanity"],["canon-west","lit-canon","dorm-canon"]);
I("classic-novel","The Great Gatsby",1925,"F. Scott Fitzgerald",86,92,97,["jazz-age","dream"],["canon-west","lit-canon"]);
I("classic-novel","Ulysses",1922,"James Joyce",44,95,98,["modernism","dublin"],["canon-west","lit-canon","postmodern-lit"]);
I("classic-novel","In Search of Lost Time",1913,"Marcel Proust",36,94,97,["memory","modernism"],["canon-west","lit-canon"]);
I("classic-novel","The Trial",1925,"Franz Kafka",56,90,93,["absurd","bureaucracy"],["canon-west","lit-canon","dystopia-canon"]);
I("classic-novel","The Metamorphosis",1915,"Franz Kafka",70,89,92,["absurd","transformation"],["canon-west","lit-canon","dorm-canon"]);
I("classic-novel","Heart of Darkness",1899,"Joseph Conrad",58,87,90,["colonialism","river"],["canon-west","lit-canon"],["apocalypse-now-1979"]);
I("classic-novel","The Grapes of Wrath",1939,"John Steinbeck",62,88,91,["depression","migration"],["canon-west","lit-canon"]);
I("classic-novel","Of Mice and Men",1937,"John Steinbeck",72,82,86,["friendship","tragedy"],["canon-west","lit-canon"]);
I("classic-novel","East of Eden",1952,"John Steinbeck",52,82,85,["family","cain-abel"],["lit-canon"]);
I("classic-novel","The Old Man and the Sea",1952,"Ernest Hemingway",70,84,87,["sea","endurance"],["canon-west","lit-canon"]);
I("classic-novel","Siddhartha",1922,"Hermann Hesse",58,78,80,["seeking","east"],["lit-canon","dorm-canon"]);
I("classic-novel","Steppenwolf",1927,"Hermann Hesse",42,74,76,["alienation"],["lit-canon","dorm-canon"]);
I("classic-novel","The Stranger",1942,"Albert Camus",68,88,91,["absurd","murder"],["canon-west","lit-canon","dorm-canon","philosophy-core"]);
I("classic-novel","Lolita",1955,"Vladimir Nabokov",58,88,92,["unreliable","style"],["canon-west","lit-canon"]);
I("classic-novel","The Catcher in the Rye",1951,"J.D. Salinger",78,86,90,["adolescence","alienation"],["canon-west","lit-canon","dorm-canon"]);
I("classic-novel","To Kill a Mockingbird",1960,"Harper Lee",84,90,94,["justice","childhood"],["canon-west","lit-canon"]);
I("classic-novel","Nineteen Eighty-Four",1949,"George Orwell",90,97,99,["dystopia","surveillance"],["canon-west","lit-canon","dystopia-canon","dorm-canon"]);
I("classic-novel","Animal Farm",1945,"George Orwell",84,92,94,["allegory","revolution"],["canon-west","lit-canon","dystopia-canon"]);
I("classic-novel","Brave New World",1932,"Aldous Huxley",76,93,95,["dystopia","pleasure"],["canon-west","lit-canon","dystopia-canon","dorm-canon"]);
I("classic-novel","Fahrenheit 451",1953,"Ray Bradbury",72,87,89,["dystopia","books"],["lit-canon","dystopia-canon","sff-canon"]);
I("classic-novel","Lord of the Flies",1954,"William Golding",76,85,88,["island","savagery"],["canon-west","lit-canon","dystopia-canon"]);
I("classic-novel","Slaughterhouse-Five",1969,"Kurt Vonnegut",62,86,89,["war","time","absurd"],["lit-canon","dorm-canon","sff-canon"]);
I("classic-novel","Catch-22",1961,"Joseph Heller",60,86,89,["war","absurd"],["lit-canon","dorm-canon"]);
I("classic-novel","One Hundred Years of Solitude",1967,"Gabriel García Márquez",68,94,97,["magical-realism","family"],["canon-west","lit-canon"]);
I("classic-novel","Things Fall Apart",1958,"Chinua Achebe",56,88,91,["colonialism","igbo"],["canon-west","lit-canon"]);
I("classic-novel","Invisible Man",1952,"Ralph Ellison",44,86,89,["identity","race"],["canon-west","lit-canon"]);
I("classic-novel","Beloved",1987,"Toni Morrison",54,90,93,["slavery","ghost"],["canon-west","lit-canon"]);
I("classic-novel","Little Women",1868,"Louisa May Alcott",70,80,84,["sisters","coming-of-age"],["canon-west","lit-canon","kids-books"]);

/* ---- Modern Literature ---- */
I("modern-lit","The Road",2006,"Cormac McCarthy",56,82,88,["apocalypse","father-son"],["lit-canon"]);
I("modern-lit","Blood Meridian",1985,"Cormac McCarthy",42,86,92,["violence","western"],["lit-canon","postmodern-lit"]);
I("modern-lit","Infinite Jest",1996,"David Foster Wallace",38,80,90,["footnotes","addiction"],["postmodern-lit","dorm-canon"]);
I("modern-lit","Gravity's Rainbow",1973,"Thomas Pynchon",26,82,90,["paranoia","war"],["postmodern-lit"]);
I("modern-lit","Norwegian Wood",1987,"Haruki Murakami",58,76,82,["loss","tokyo"],["lit-canon"]);
I("modern-lit","Kafka on the Shore",2002,"Haruki Murakami",54,74,80,["surreal","cats"],["lit-canon"]);
I("modern-lit","The Handmaid's Tale",1985,"Margaret Atwood",70,88,90,["dystopia","gender"],["dystopia-canon","sff-canon"]);
I("modern-lit","Midnight's Children",1981,"Salman Rushdie",42,84,88,["india","magical-realism"],["lit-canon"]);
I("modern-lit","The God of Small Things",1997,"Arundhati Roy",44,78,82,["india","family"],["lit-canon"]);
I("modern-lit","The Remains of the Day",1989,"Kazuo Ishiguro",44,80,85,["restraint","memory"],["lit-canon"]);
I("modern-lit","Never Let Me Go",2005,"Kazuo Ishiguro",52,80,85,["clones","melancholy"],["lit-canon","sff-canon"]);
I("modern-lit","Atonement",2001,"Ian McEwan",48,76,80,["war","guilt"],["lit-canon"]);
I("modern-lit","Cloud Atlas",2004,"David Mitchell",46,76,82,["nested","reincarnation","frame-story"],["sff-canon","postmodern-lit"]);
I("modern-lit","Life of Pi",2001,"Yann Martel",64,74,78,["sea","faith","frame-story"],["lit-canon"]);
I("modern-lit","The Kite Runner",2003,"Khaled Hosseini",66,74,78,["afghanistan","guilt"],["lit-canon"]);
I("modern-lit","The Alchemist",1988,"Paulo Coelho",78,70,74,["fable","quest"],[]);
I("modern-lit","The Secret History",1992,"Donna Tartt",48,72,80,["campus","murder"],["lit-canon"]);
I("modern-lit","A Little Life",2015,"Hanya Yanagihara",44,66,74,["trauma","friendship"],["lit-canon"]);
I("modern-lit","Normal People",2018,"Sally Rooney",54,64,72,["romance","class"],["lit-canon"]);
I("modern-lit","My Brilliant Friend",2011,"Elena Ferrante",44,74,80,["naples","friendship"],["lit-canon"]);
I("modern-lit","American Psycho",1991,"Bret Easton Ellis",54,74,80,["satire","violence"],["postmodern-lit","dorm-canon"],["american-psycho-2000"]);
I("modern-lit","Fight Club",1996,"Chuck Palahniuk",58,72,78,["masculinity","satire"],["dorm-canon"],["fight-club-1999"]);
I("modern-lit","Trainspotting",1993,"Irvine Welsh",44,70,76,["addiction","edinburgh"],["dorm-canon"],["trainspotting-1996"]);
I("modern-lit","All the Light We Cannot See",2014,"Anthony Doerr",50,66,72,["ww2","radio"],["lit-canon","wwii-memory"]);
I("modern-lit","The Book Thief",2005,"Markus Zusak",58,70,75,["ww2","death-narrator"],["ya-wave","wwii-memory"]);

/* ---- Speculative Fiction ---- */
I("sff","The Hobbit",1937,"J.R.R. Tolkien",86,90,94,["fantasy","quest"],["high-fantasy","sff-canon","kids-books"]);
I("sff","The Lord of the Rings",1954,"J.R.R. Tolkien",90,97,100,["fantasy","epic"],["high-fantasy","sff-canon","canon-west"]);
I("sff","A Game of Thrones",1996,"George R.R. Martin",76,84,92,["fantasy","politics"],["high-fantasy","sff-canon"],["game-of-thrones-2011"]);
I("sff","Harry Potter (series)",1997,"J.K. Rowling",97,92,96,["fantasy","school"],["high-fantasy","kids-books","ya-wave"],["harry-potter-and-the-philosophers-stone-2001"]);
I("sff","The Chronicles of Narnia",1950,"C.S. Lewis",80,84,88,["fantasy","allegory"],["high-fantasy","kids-books"]);
I("sff","His Dark Materials",1995,"Philip Pullman",58,78,84,["fantasy","daemon"],["high-fantasy","ya-wave"]);
I("sff","A Wizard of Earthsea",1968,"Ursula K. Le Guin",42,80,88,["fantasy","names"],["high-fantasy","sff-canon"]);
I("sff","The Left Hand of Darkness",1969,"Ursula K. Le Guin",36,82,90,["gender","scifi"],["sff-canon","space-scifi"]);
I("sff","The Wheel of Time",1990,"Robert Jordan",44,66,78,["fantasy","epic"],["high-fantasy"]);
I("sff","The Name of the Wind",2007,"Patrick Rothfuss",48,64,76,["fantasy","frame-story"],["high-fantasy"]);
I("sff","Mistborn: The Final Empire",2006,"Brandon Sanderson",48,62,76,["fantasy","heist"],["high-fantasy"]);
I("sff","The Way of Kings",2010,"Brandon Sanderson",46,62,76,["fantasy","epic"],["high-fantasy"]);
I("sff","Discworld (series)",1983,"Terry Pratchett",56,78,86,["fantasy","satire"],["high-fantasy","brit-comedy"]);
I("sff","Good Omens",1990,"Terry Pratchett & Neil Gaiman",52,68,74,["apocalypse","comedy"],["high-fantasy","brit-comedy"]);
I("sff","American Gods",2001,"Neil Gaiman",50,70,78,["myth","america"],["sff-canon"]);
I("sff","The Witcher Saga",1993,"Andrzej Sapkowski",52,66,76,["fantasy","monster-hunter"],["high-fantasy"],["the-witcher-3-wild-hunt-2015"]);
I("sff","Dune",1965,"Frank Herbert",74,92,97,["scifi","desert","empire"],["sff-canon","space-scifi"],["dune-2021"]);
I("sff","Foundation",1951,"Isaac Asimov",52,86,92,["scifi","psychohistory"],["sff-canon","space-scifi"]);
I("sff","Ender's Game",1985,"Orson Scott Card",60,78,86,["scifi","war-game"],["sff-canon","space-scifi"]);
I("sff","Hyperion",1989,"Dan Simmons",38,72,84,["scifi","pilgrimage","frame-story"],["sff-canon","space-scifi"]);
I("sff","Neuromancer",1984,"William Gibson",48,86,92,["cyberpunk","matrix"],["cyberpunk","sff-canon"],["the-matrix-1999"]);
I("sff","Snow Crash",1992,"Neal Stephenson",42,76,84,["cyberpunk","metaverse"],["cyberpunk","sff-canon"]);
I("sff","Do Androids Dream of Electric Sheep?",1968,"Philip K. Dick",46,82,88,["androids","empathy"],["cyberpunk","sff-canon"],["blade-runner-1982"]);
I("sff","A Clockwork Orange",1962,"Anthony Burgess",54,82,86,["dystopia","nadsat"],["dystopia-canon","dorm-canon"],["a-clockwork-orange-1971"]);
I("sff","The Hitchhiker's Guide to the Galaxy",1979,"Douglas Adams",74,84,90,["comedy","scifi","42"],["sff-canon","brit-comedy","dorm-canon"]);
I("sff","The Martian",2011,"Andy Weir",64,72,80,["mars","survival"],["space-scifi"],["the-martian-2015"]);
I("sff","Project Hail Mary",2021,"Andy Weir",56,68,78,["space","first-contact"],["space-scifi"],[],"Astrophage; the singing. Amaze.");
I("sff","The Three-Body Problem",2008,"Liu Cixin",58,82,88,["scifi","contact","physics"],["space-scifi","sff-canon"]);
I("sff","The Time Machine",1895,"H.G. Wells",58,84,88,["time-travel","victorian"],["sff-canon","canon-west"]);
I("sff","The War of the Worlds",1898,"H.G. Wells",66,86,89,["invasion","victorian"],["sff-canon","canon-west"],["the-war-of-the-worlds-broadcast-1938"]);
I("sff","Twenty Thousand Leagues Under the Seas",1870,"Jules Verne",56,82,85,["sea","submarine"],["sff-canon","canon-west"]);
I("sff","Station Eleven",2014,"Emily St. John Mandel",42,66,74,["pandemic","shakespeare"],["sff-canon"]);
I("sff","More Than This",2013,"Patrick Ness",26,50,62,["afterlife","simulation"],["ya-wave"],[],"Opens with a drowning; wakes into an empty England. Nozick's experience machine, aimed at teenagers.");
I("sff","Ready Player One",2011,"Ernest Cline",56,58,64,["vr","nostalgia"],["ya-wave","gamer-core"]);
I("sff","The Hunger Games",2008,"Suzanne Collins",82,76,84,["dystopia","arena"],["ya-wave","dystopia-canon"]);

/* ---- Crime & Thriller ---- */
I("crime-thriller","The Adventures of Sherlock Holmes",1892,"Arthur Conan Doyle",84,92,98,["detective","deduction"],["crime-noir","canon-west"],["sherlock-2010"]);
I("crime-thriller","And Then There Were None",1939,"Agatha Christie",72,86,94,["mystery","island"],["crime-noir"]);
I("crime-thriller","Murder on the Orient Express",1934,"Agatha Christie",74,84,92,["mystery","train"],["crime-noir"]);
I("crime-thriller","The Big Sleep",1939,"Raymond Chandler",40,80,90,["noir","la"],["crime-noir"]);
I("crime-thriller","The Maltese Falcon",1930,"Dashiell Hammett",38,78,88,["noir","macguffin"],["crime-noir"]);
I("crime-thriller","The Talented Mr. Ripley",1955,"Patricia Highsmith",42,74,84,["imposter","italy"],["crime-noir"]);
I("crime-thriller","The Godfather",1969,"Mario Puzo",58,78,84,["mafia","family"],["crime-noir"],["the-godfather-1972"]);
I("crime-thriller","The Silence of the Lambs",1988,"Thomas Harris",54,74,82,["serial-killer","profiler"],["crime-noir"],["the-silence-of-the-lambs-1991"]);
I("crime-thriller","In Cold Blood",1966,"Truman Capote",44,84,90,["true-crime","kansas"],["crime-noir","true-crime"]);
I("crime-thriller","The Girl with the Dragon Tattoo",2005,"Stieg Larsson",64,70,78,["hacker","sweden"],["crime-noir"]);
I("crime-thriller","Gone Girl",2012,"Gillian Flynn",64,70,80,["marriage","twist"],["crime-noir"]);
I("crime-thriller","The Da Vinci Code",2003,"Dan Brown",80,62,68,["conspiracy","symbols"],[]);
I("crime-thriller","No Country for Old Men",2005,"Cormac McCarthy",44,74,80,["border","fate"],["crime-noir"],["no-country-for-old-men-2007"]);

/* ---- Children's & YA ---- */
I("ya-childrens","The Little Prince",1943,"Antoine de Saint-Exupéry",88,92,96,["fable","planet"],["kids-books","canon-west"]);
I("ya-childrens","Alice's Adventures in Wonderland",1865,"Lewis Carroll",86,92,96,["nonsense","dream"],["kids-books","canon-west"]);
I("ya-childrens","Winnie-the-Pooh",1926,"A.A. Milne",84,84,90,["bear","hundred-acre"],["kids-books"]);
I("ya-childrens","Charlotte's Web",1952,"E.B. White",70,80,86,["spider","farm"],["kids-books"]);
I("ya-childrens","Matilda",1988,"Roald Dahl",76,78,86,["books","telekinesis"],["kids-books"]);
I("ya-childrens","Charlie and the Chocolate Factory",1964,"Roald Dahl",82,80,88,["candy","golden-ticket"],["kids-books"]);
I("ya-childrens","The BFG",1982,"Roald Dahl",70,72,80,["giant","dreams"],["kids-books"]);
I("ya-childrens","Where the Wild Things Are",1963,"Maurice Sendak",72,82,88,["picture-book","wild"],["kids-books"]);
I("ya-childrens","The Very Hungry Caterpillar",1969,"Eric Carle",80,78,86,["picture-book"],["kids-books"]);
I("ya-childrens","The Gruffalo",1999,"Julia Donaldson",64,66,78,["picture-book","rhyme"],["kids-books"]);
I("ya-childrens","The Wind in the Willows",1908,"Kenneth Grahame",58,74,80,["riverbank","toad"],["kids-books"]);
I("ya-childrens","Peter Pan",1911,"J.M. Barrie",80,82,86,["neverland","flying"],["kids-books","canon-west"]);
I("ya-childrens","Treasure Island",1883,"Robert Louis Stevenson",70,82,86,["pirates","map"],["kids-books","canon-west"]);
I("ya-childrens","The Secret Garden",1911,"Frances Hodgson Burnett",58,72,78,["garden","healing"],["kids-books"]);
I("ya-childrens","Anne of Green Gables",1908,"L.M. Montgomery",62,76,82,["orphan","imagination"],["kids-books"]);
I("ya-childrens","Percy Jackson and the Olympians",2005,"Rick Riordan",66,62,76,["myth","camp"],["ya-wave","kids-books"]);
I("ya-childrens","Twilight",2005,"Stephenie Meyer",76,62,70,["vampire","romance"],["ya-wave"]);
I("ya-childrens","The Fault in Our Stars",2012,"John Green",62,58,68,["illness","romance"],["ya-wave"]);
I("ya-childrens","Wonder",2012,"R.J. Palacio",56,56,66,["kindness","school"],["ya-wave","kids-books"]);
I("ya-childrens","Holes",1998,"Louis Sachar",58,62,72,["camp","curse"],["kids-books","ya-wave"]);
I("ya-childrens","Diary of a Wimpy Kid",2007,"Jeff Kinney",72,54,66,["school","cartoon"],["kids-books"]);
I("ya-childrens","Goosebumps (series)",1992,"R.L. Stine",70,60,70,["horror","series"],["kids-books","horror-canon"]);

/* ---- Comics & Manga ---- */
I("comics-manga","Watchmen",1986,"Alan Moore & Dave Gibbons",56,88,98,["superhero","deconstruction"],["comics-canon","dorm-canon"]);
I("comics-manga","The Dark Knight Returns",1986,"Frank Miller",44,80,92,["batman","grim"],["comics-canon"],["the-dark-knight-2008"]);
I("comics-manga","Maus",1980,"Art Spiegelman",48,90,96,["holocaust","memoir"],["comics-canon","wwii-memory"]);
I("comics-manga","Persepolis",2000,"Marjane Satrapi",40,78,86,["iran","memoir"],["comics-canon"]);
I("comics-manga","The Sandman",1989,"Neil Gaiman",44,78,90,["dream","myth"],["comics-canon"]);
I("comics-manga","V for Vendetta",1982,"Alan Moore & David Lloyd",46,74,84,["dystopia","mask"],["comics-canon","dystopia-canon"]);
I("comics-manga","Calvin and Hobbes",1985,"Bill Watterson",64,84,94,["strip","childhood"],["comics-canon","kids-canon"]);
I("comics-manga","Peanuts",1950,"Charles M. Schulz",78,88,94,["strip","melancholy"],["comics-canon","kids-canon"]);
I("comics-manga","The Adventures of Tintin",1929,"Hergé",70,84,90,["adventure","clear-line"],["comics-canon","kids-books"]);
I("comics-manga","Asterix",1959,"Goscinny & Uderzo",68,78,86,["gaul","puns"],["comics-canon","kids-books"]);
I("comics-manga","Akira",1982,"Katsuhiro Otomo",50,86,94,["cyberpunk","neo-tokyo"],["anime-deep","cyberpunk","comics-canon"],["akira-1988"]);
I("comics-manga","Dragon Ball",1984,"Akira Toriyama",82,86,94,["shonen","training"],["anime-gateway","comics-canon"],["dragon-ball-z-1989"]);
I("comics-manga","One Piece",1997,"Eiichiro Oda",80,80,92,["shonen","pirates"],["anime-gateway","comics-canon"]);
I("comics-manga","Naruto",1999,"Masashi Kishimoto",80,74,88,["shonen","ninja"],["anime-gateway","comics-canon"]);
I("comics-manga","Berserk",1989,"Kentaro Miura",46,76,90,["dark-fantasy","struggle"],["anime-deep","comics-canon"]);
I("comics-manga","Attack on Titan",2009,"Hajime Isayama",68,72,86,["titans","walls"],["anime-gateway","comics-canon"],["attack-on-titan-2013"]);

/* ---- Poetry ---- */
I("poetry","Shakespeare's Sonnets",1609,"William Shakespeare",66,92,97,["love","time"],["poetry-canon","canon-west"]);
I("poetry","Leaves of Grass",1855,"Walt Whitman",44,86,92,["multitudes","america"],["poetry-canon","canon-west"],[],"I contain multitudes.");
I("poetry","The Waste Land",1922,"T.S. Eliot",40,90,96,["modernism","fragments"],["poetry-canon","canon-west"]);
I("poetry","The Raven",1845,"Edgar Allan Poe",70,82,88,["gothic","nevermore"],["poetry-canon","canon-west"]);
I("poetry","The Complete Poems of Emily Dickinson",1890,"Emily Dickinson",48,86,92,["dashes","interiority"],["poetry-canon","canon-west"]);
I("poetry","The Essential Rumi",1273,"Rumi",56,84,88,["sufi","love"],["poetry-canon"]);
I("poetry","Howl",1956,"Allen Ginsberg",42,80,86,["beat","protest"],["poetry-canon","dorm-canon"]);
I("poetry","Ariel",1965,"Sylvia Plath",42,78,86,["confessional"],["poetry-canon"]);
I("poetry","The Odes of John Keats",1819,"John Keats",38,82,88,["romantic","beauty"],["poetry-canon","canon-west"]);
I("poetry","Milk and Honey",2014,"Rupi Kaur",54,44,52,["instagram","spare"],["internet-native"]);

/* ---- Plays (as texts) ---- */
I("plays","Hamlet",1601,"William Shakespeare",84,98,100,["tragedy","revenge"],["theatre-canon","canon-west"]);
I("plays","Macbeth",1606,"William Shakespeare",80,94,97,["tragedy","ambition"],["theatre-canon","canon-west"]);
I("plays","Romeo and Juliet",1595,"William Shakespeare",88,94,97,["tragedy","love"],["theatre-canon","canon-west"],["west-side-story-1957"]);
I("plays","King Lear",1606,"William Shakespeare",58,92,95,["tragedy","inheritance"],["theatre-canon","canon-west"]);
I("plays","Othello",1603,"William Shakespeare",62,90,93,["tragedy","jealousy"],["theatre-canon","canon-west"]);
I("plays","A Midsummer Night's Dream",1595,"William Shakespeare",70,88,91,["comedy","fairies"],["theatre-canon","canon-west"]);
I("plays","Oedipus Rex",-429,"Sophocles",54,92,96,["tragedy","fate"],["theatre-canon","canon-west"]);
I("plays","Antigone",-441,"Sophocles",46,86,90,["tragedy","law"],["theatre-canon","canon-west"]);
I("plays","Death of a Salesman",1949,"Arthur Miller",52,86,92,["american-dream"],["theatre-canon"]);
I("plays","The Crucible",1953,"Arthur Miller",56,84,88,["witch-trials","allegory"],["theatre-canon"]);
I("plays","A Streetcar Named Desire",1947,"Tennessee Williams",52,84,90,["desire","new-orleans"],["theatre-canon"]);
I("plays","Waiting for Godot",1953,"Samuel Beckett",50,90,96,["absurd","waiting"],["theatre-canon","canon-west"]);
I("plays","The Importance of Being Earnest",1895,"Oscar Wilde",58,84,90,["comedy","wit"],["theatre-canon","brit-comedy"]);
I("plays","A Doll's House",1879,"Henrik Ibsen",44,86,92,["marriage","door-slam"],["theatre-canon","canon-west"]);
I("plays","Pygmalion",1913,"George Bernard Shaw",42,78,84,["class","speech"],["theatre-canon"],["my-fair-lady-1956"]);

/* ---- Nonfiction ---- */
I("nonfiction","On the Origin of Species",1859,"Charles Darwin",60,98,100,["evolution","science"],["canon-west","big-ideas"]);
I("nonfiction","A Brief History of Time",1988,"Stephen Hawking",70,86,92,["cosmology","time"],["big-ideas"]);
I("nonfiction","Cosmos",1980,"Carl Sagan",56,84,90,["astronomy","wonder"],["big-ideas","space-race"],["cosmos-1980"]);
I("nonfiction","A Short History of Nearly Everything",2003,"Bill Bryson",52,72,80,["science","tour"],["big-ideas"]);
I("nonfiction","The Selfish Gene",1976,"Richard Dawkins",50,84,90,["evolution","memes"],["big-ideas"]);
I("nonfiction","Silent Spring",1962,"Rachel Carson",42,86,90,["environment"],["big-ideas"]);
I("nonfiction","Sapiens",2011,"Yuval Noah Harari",72,74,84,["history","species"],["big-ideas"]);
I("nonfiction","Guns, Germs, and Steel",1997,"Jared Diamond",52,74,82,["geography","history"],["big-ideas"]);
I("nonfiction","Thinking, Fast and Slow",2011,"Daniel Kahneman",58,80,88,["cognition","bias"],["big-ideas"]);
I("nonfiction","Freakonomics",2005,"Levitt & Dubner",56,64,74,["economics","incentives"],["big-ideas"]);
I("nonfiction","Outliers",2008,"Malcolm Gladwell",60,62,72,["success","10000-hours"],["big-ideas"]);
I("nonfiction","Atomic Habits",2018,"James Clear",68,56,66,["habits","systems"],["big-ideas"]);
I("nonfiction","The Diary of a Young Girl",1947,"Anne Frank",82,94,97,["holocaust","diary"],["canon-west","wwii-memory"]);
I("nonfiction","Man's Search for Meaning",1946,"Viktor Frankl",58,84,90,["holocaust","meaning"],["big-ideas","wwii-memory"]);
I("nonfiction","Into the Wild",1996,"Jon Krakauer",52,68,78,["wilderness","alaska"],["big-ideas"]);
I("nonfiction","Into Thin Air",1997,"Jon Krakauer",44,66,78,["everest","disaster"],["big-ideas"]);
I("nonfiction","Educated",2018,"Tara Westover",52,64,74,["memoir","family"],["big-ideas"]);
I("nonfiction","When Breath Becomes Air",2016,"Paul Kalanithi",48,62,72,["memoir","mortality"],["big-ideas"]);
I("nonfiction","Gödel, Escher, Bach",1979,"Douglas Hofstadter",36,80,90,["recursion","minds"],["big-ideas","philosophy-core"]);
I("nonfiction","The Structure of Scientific Revolutions",1962,"Thomas Kuhn",30,84,90,["paradigms","science"],["big-ideas","philosophy-core"]);

/* ---- Philosophy & Ideas ---- */
I("ideas","The Republic",-375,"Plato",58,97,100,["justice","cave"],["philosophy-core","canon-west"]);
I("ideas","Nicomachean Ethics",-340,"Aristotle",40,92,96,["virtue","flourishing"],["philosophy-core","canon-west"]);
I("ideas","Meditations",180,"Marcus Aurelius",66,88,92,["stoicism","discipline"],["philosophy-core","canon-west"]);
I("ideas","Tao Te Ching",-400,"Laozi",62,92,96,["tao","paradox"],["philosophy-core"]);
I("ideas","The Analects",-475,"Confucius",50,92,95,["ethics","order"],["philosophy-core"]);
I("ideas","The Art of War",-500,"Sun Tzu",74,88,90,["strategy"],["philosophy-core"]);
I("ideas","The Prince",1532,"Niccolò Machiavelli",64,90,93,["power","statecraft"],["philosophy-core","canon-west"]);
I("ideas","Leviathan",1651,"Thomas Hobbes",36,88,92,["state","contract"],["philosophy-core","canon-west"]);
I("ideas","Critique of Pure Reason",1781,"Immanuel Kant",30,94,98,["epistemology","limits"],["philosophy-core","canon-west"]);
I("ideas","Thus Spoke Zarathustra",1883,"Friedrich Nietzsche",52,90,94,["ubermensch","recurrence"],["philosophy-core","canon-west","dorm-canon"],[],"The appearance of laws needs not necessitate necessity — argue with him, not past him.");
I("ideas","Beyond Good and Evil",1886,"Friedrich Nietzsche",46,88,92,["morality","perspectivism"],["philosophy-core","canon-west"]);
I("ideas","The Communist Manifesto",1848,"Marx & Engels",62,94,96,["class","revolution"],["philosophy-core","canon-west"]);
I("ideas","On Liberty",1859,"John Stuart Mill",38,86,90,["freedom","harm"],["philosophy-core","canon-west"]);
I("ideas","Walden",1854,"Henry David Thoreau",50,80,84,["simplicity","woods"],["philosophy-core","canon-west"]);
I("ideas","The Second Sex",1949,"Simone de Beauvoir",40,88,92,["feminism","other"],["philosophy-core","canon-west"]);
I("ideas","The Myth of Sisyphus",1942,"Albert Camus",48,84,88,["absurd","revolt"],["philosophy-core","dorm-canon"]);
I("ideas","Anarchy, State, and Utopia",1974,"Robert Nozick",26,78,86,["libertarianism","experience-machine"],["philosophy-core"],[],"Home of the experience machine — would you plug in? The knot-untangling counterargument lives here too.");
